Project-JJ/config/routes.rb
Rails.application.routes.draw do
  resources :user_fund_projects do
    member do
      get :confirm_email
    end
  end
  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}	
  resources :user_projects
  resources :categories
  resources :user_roles
  resources :users
  resources :wishlists
  resources :projects
  resources :promises
  root 'application#index'
  post 'projects/search' => 'projects#search', as: 'search_projects'
  post 'categories/search' => 'categories#search', as: 'search_categories'
  get 'projects/:id/promises' => 'projects#promises', as: 'promisesp'
  get 'projects/:id/promises/new' => 'projects#promisesnew', as:'promisesnew'
  get '/:token/confirm_email/', :to => "user_fund_projects#confirm_email", as: 'confirm_email'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Project-JJ/app/models/category.rb
class Category < ApplicationRecord
	has_many :projects
	def self.search(search)
	  if search
	    where('name LIKE ?', "%#{search}%")
	  else
	    all
	  end
	end
end

Project-JJ/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end
  def search
    @categories = Category.search(params[:query])
    render 'index'
  end
  # GET /categories/1
  # GET /categories/1.json
  def show
    @projects = Project.all
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

Project-JJ/app/helpers/categories_helper.rb
module CategoriesHelper
end

Project-JJ/app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Project-JJ/app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

Project-JJ/app/views/categories/index.html.erb
<!DOCTYPE html>

<head>
<style>

	#allcategories {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

#allcategories td, #allcategories th {
    border: 1px solid #ddd;
    padding: 8px;
    text-align: center;
}

#allcategories tr:nth-child(even){background-color: #f2f2f2;}



#allcategories th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: center;
    background-color: #004C99;
    color: white;
}


</style>
<h3>Search Categories</h3>
<%= form_tag search_categories_path do |form|%>
 		<input class='search full-width' id='searchbar' name='query' placeholder='Search Categories' type='string' autocomplete='off'>
		<div class="field">
  		</div>
<% end %>

</head>
<body>

<div>
<h1>Categories</h1>

<table id ="allcategories"  width=100%  >

  <thead>
    <tr>
      <th>Name</th>      
      <th colspan="3">Action</th>
      
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        
        <td><%= link_to 'Show', category %></td>
	<%- if current_user.try(:admin?) %>
		<td><%= link_to 'Edit', edit_category_path(category) %></td>
		<td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>
<%- if current_user.try(:admin?) %>
<%= link_to 'New Category', new_category_path %>
<% end %>

</html>



 

</body>

Project-JJ/app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

Project-JJ/app/views/categories/show.html.erb
<!DOCTYPE html>
<p id="notice"><%= notice %></p>
<p>

  <strong>Name:</strong>
  <%= @category.name %>
</p>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Donationamount</th>
      <th>Category</th>
      <th>User</th>
      <th>Deliverydate</th>
      <th>Promise</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
	<% if project.category == @category %>
	
	      <tr>
		<td><%= project.title %></td>
		<td><%= project.description %></td>
		<td><%= project.donationamount %></td>
		<td><%= project.category.name %></td>
		<td><%= project.user_id %></td>
		<td><%= project.deliverydate %></td>
		<td><%= project.promise_id %></td>
		<td><%= link_to 'Show', project %></td>
		<td><%= link_to 'Edit', edit_project_path(project) %></td>
		<td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	<% end %>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>