Project-JJ/config/routes.rb
Rails.application.routes.draw do
  resources :user_fund_projects do
    member do
      get :confirm_email
    end
  end
  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}	
  resources :user_projects
  resources :categories
  resources :user_roles
  resources :users
  resources :wishlists
  resources :projects
  resources :promises
  root 'application#index'
  post 'projects/search' => 'projects#search', as: 'search_projects'
  post 'categories/search' => 'categories#search', as: 'search_categories'
  get 'projects/:id/promises' => 'projects#promises', as: 'promisesp'
  get 'projects/:id/promises/new' => 'projects#promisesnew', as:'promisesnew'
  get '/:token/confirm_email/', :to => "user_fund_projects#confirm_email", as: 'confirm_email'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Project-JJ/app/models/project.rb
class Project < ApplicationRecord
	belongs_to :user
	belongs_to :category
	has_one :promise
	has_and_belongs_to_many :wishlists
	validates :title, presence: true
	validates :category_id, presence: true
	validates :description, presence: true
	has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", large: "600x600>"}
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	

	def self.search(search)
	  if search
	    where('title LIKE ? or description LIKE ? ', "%#{search}%","%#{search}%")
	  else
	    all
	  end
	end


	
end

Project-JJ/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
load_and_authorize_resource
skip_authorize_resource :only => :promises
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    
    @projects = Project.all
    respond_to do |format|

      format.html # index.html.erb

    end
  end
  def promises
	@promises = Promise.where(:project_id => @project.id)
	
  end

 def promisesnew
	
  end

  def search
    @projects = Project.search(params[:query])
    render 'index'

  end

  # GET /projects/1
  # GET /projects/1.json
  def show
	@Suma = UserFundProject.where(:project_id => @project.id,:email_confirmed => true).sum(:amount)
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end 

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:title, :description, :donationamount, :category_id, :user_id, :deliverydate, :promise_id, :image, :donation, :yourdonation, :mark)
    end
end

Project-JJ/app/helpers/projects_helper.rb
module ProjectsHelper
end

Project-JJ/app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :donationamount %>
    <%= form.number_field :donationamount %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select :category_id, Category.all, :id, :name, include_blank: true %>
  </div>

<%= form.hidden_field :user_id, value: current_user.id %>
<%= form.hidden_field :donation, value: 0 %>

  <div class="field">
    <%= form.label :deliverydate %>
    <%= form.datetime_select :deliverydate %>
  </div>

<% if user_signed_in? && current_user.admin %>
    <div class="field">
      <%= label_tag :outstanding %>
	    <%= form.check_box :mark %>
    </div>
<%end%>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Project-JJ/app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

Project-JJ/app/views/projects/index.html.erb
<!DOCTYPE html>



<h1>Projects</h1>

<style>
	#allprojects {
    font-family: "Trebuchet MS", Arial, Helvetica, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

#allprojects td, #allprojects th {
    border: 1px solid #ddd;
    padding: 8px;
    text-align: center;
}

#allprojects tr:nth-child(even){background-color: #f2f2f2;}



#allprojects th {
    padding-top: 12px;
    padding-bottom: 12px;
    text-align: center;
    background-color: #004C99;
    color: white;
}
</style>
<body>

<table id="allprojects">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Donationamount</th>
      <th>Category</th>
      <th>User</th>
      <th>Deliverydate</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.donationamount %></td>
        <td><%= project.category.name %></td>
        <td><%= project.user_id %></td>
        <td><%= project.deliverydate %></td>
        <td><%= link_to 'Show', project %></td>
	<% if project.user_id == current_user.try(:id) or current_user.try(:admin) %> %>
        	<td><%= link_to 'Edit', edit_project_path(project) %></td>
        	<td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>




</body>



</html>

Project-JJ/app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

Project-JJ/app/views/projects/promises.html.erb
<p id="notice"><%= notice %></p>

<h1>Promises</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @promises.each do |promise| %>
      <tr>
        <td><%= promise.description %></td>
        <td><%= promise.price %></td>
        <td><%= link_to 'Show', promise %></td>
	<td><%= button_to "Buy", :controller => "user_fund_projects", :action => "create", :user_id => current_user.try(:id), :project_id => @project.id, :amount => promise.price, :method => :"post" %>
	<td><%- if current_user.id == @project.user_id %></td>
        <td><%= link_to 'Edit', edit_promise_path(promise) %></td>
        <td><%= link_to 'Destroy', promise, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

Project-JJ/app/views/projects/promisesnew.html.erb
<h1>New Promise</h1>
<%=form_tag(controller: 'promises', action: 'create', method: 'post') do %>
 <div class="field">
<%= label_tag(:descriptiom, "Description:") %>
<%= text_area_tag :description %>
</div>

<%= hidden_field_tag :project_id, @project.id %>
 <div class="field">
<%= label_tag(:price, "Price:") %>
<%= number_field_tag :price %>
</div>
<%= submit_tag "Donation" %>   
<% end %>

Project-JJ/app/views/projects/show.html.erb
<!DOCTYPE html>
<head>
<style>


html, body { height: 100%; padding: 0; margin: 0; }
div { width: 50%; height: 50%; float: left; }
#div1 { background: #0080FF; }
#descriptiondiv { background: #3399FF; }
#specificationsdiv { background: #66B2FF; }
#div4 { background: #99CCFF; }
.style-image { border-right: 10px; solid #000; margin:auto;}
.linkbutton {background-color:black;
box-shadow: 0 5px 0 grey;
color: white;
padding 1em 1.5em;
position: relative;
font-size: 40px;
}
.cornerbuttons {background-color: green;
border-radius: 12px;
font-size: 40px;
color: white;
cursor: pointer;
}
.donationbutton {background-color: green;
border-radius: 12px;
font-size: 40px;
color: white;
cursor: pointer;
}



</style>
</head>
<body>


<div id="div1">
<p id="notice"><%= notice %></p>

  <h1> <strong>Project name:</strong> <%= @project.title %></h1>
</p>
<%= image_tag @project.image.url(:large), :class => "style-image" %>


<%- if current_user.try(:id) == @project.user_id  or current_user.try(:admin?) %>
	<%= link_to 'Edit', edit_project_path(@project) %> |
<% end %>
<%= link_to 'Back', projects_path %>
</div>
<div id="descriptiondiv">
	<p>
  		<h2> <strong>Description:</strong> </h2>
		<%= @project.description %>   		
	</p>
</div>
<div id="specificationsdiv">
<p>
  <h2> <strong>Category:</strong> <%= @project.category.name %> </h2>
  
</p>

<p>
  <h2> <strong>User:</strong> <%= @project.user_id %> </h2>   
</p>

<p>
  <h3> <strong>Deliverydate:</strong> <%= @project.deliverydate %> </h3>
  
</p>
<p>
  <strong>Donationamount:</strong>
  <%= @project.donationamount %>
</p>
  <strong>Donation:</strong>
  <%= @Suma %>
</p>

</div>
<div id="div4">

<%= link_to 'Check promises here.', promisesp_path, class: "linkbutton" %>
<% if @project.user_id == current_user.try(:id) %>

<% end %>
<%=form_tag(controller: 'user_fund_projects', action: 'create', method: 'post') do %>
<%= hidden_field_tag :user_id, current_user.try(:id) %> 
<%= hidden_field_tag :project_id, @project.id %>
<%= number_field_tag :amount %>
<%= submit_tag "Donation", class: "donationbutton" %>   
<% end %>
<td><%= button_to "Add project to wishlist", {:controller => "wishlists", :action => "create", :user_id => current_user.try(:id), :project_id => @project.id, :method => :"post"}, {class: "cornerbuttons"} %> </td>
<%= link_to 'Create a Promise', promisesnew_path %>
</div>

</body>

</html>