Project-JJ/config/routes.rb
Rails.application.routes.draw do
  resources :user_fund_projects do
    member do
      get :confirm_email
    end
  end
  devise_for :users, :controllers => {:registrations => "users/registrations", :omniauth_callbacks => "users/omniauth_callbacks"}	
  resources :user_projects
  resources :categories
  resources :user_roles
  resources :users
  resources :wishlists
  resources :projects
  resources :promises
  root 'application#index'
  post 'projects/search' => 'projects#search', as: 'search_projects'
  post 'categories/search' => 'categories#search', as: 'search_categories'
  get 'projects/:id/promises' => 'projects#promises', as: 'promisesp'
  get 'projects/:id/promises/new' => 'projects#promisesnew', as:'promisesnew'
  get '/:token/confirm_email/', :to => "user_fund_projects#confirm_email", as: 'confirm_email'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

Project-JJ/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  	devise  :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]
	has_many :projects	
	has_one :wishlists
        has_one :user_role
	def self.new_with_session(params, session)
  		super.tap do |user|
    		if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      		user.email = data["email"] if user.email.blank?
    		end
 	end
	end
	def self.from_omniauth(auth)
	  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.email = auth.info.email
	    user.password = Devise.friendly_token[0,20]
	    user.name = auth.info.name 
	    
	  end
	end
end

Project-JJ/app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController

  def sign_up_params
    params.require(:user).permit(:username, :description, :name,  :email, :password, :lastname, :telephone, :country, :profession, :age, :password_confirmation)
  end

  def account_update_params
     params.require(:user).permit(:username, :description, :name,  :email, :password, :lastname, :telephone, :country, :profession, :age, :password_confirmation, :current_password)
  end
end 

Project-JJ/app/controllers/users_controller.rb
class UsersController < ApplicationController
load_and_authorize_resource
before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
     @projects = Project.all
	@user_fund_projects = UserFundProject.where(:email_confirmed => true)
	
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user       
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:userprofile_id)
    end
end

Project-JJ/app/helpers/users_helper.rb
module UsersHelper
end

Project-JJ/app/views/users/_form.html.erb
<%= form_with(model: user, local: true) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :userprofile_id %>
    <%= form.number_field :userprofile_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

Project-JJ/app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

Project-JJ/app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Userprofile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

Project-JJ/app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

Project-JJ/app/views/users/show.html.erb
<style>


html, body { height: 100%; padding: 0; margin: 0; }
div { width: 50%; height: 50%; float: left; }
#divbottom {width: 100%; height: 50%; float: bottom;}
#div1 { width: 30%; background: #0080FF; }
#descriptiondiv { width: 70%; background: #3399FF; }
#specificationsdiv { background: #66B2FF; }
table {
  border-collapse: separate;  
  width: 100%;
}
table td, table th {
	border: 1px solid #ddd;
	
}
table tr:nth-child(even){background-color: #f2f2f2;}

table th {padding-top: 12px;
    padding-bottom: 12px;
    text-align: center;
    background-color: #000066;
    color: white;
}

	


</style>





<div id="div1">
<h1> User information </h1>
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.name %>
</p>
<p>
<strong>Last name:</strong>
   <%= @user.lastname %>
</p>
<p>
<strong>eMail:</strong>
  <%= @user.email %>
</p>
<p>
<strong>Telephone:</strong>
  <%= @user.telephone %>
</p>
<p>
<strong>Description:</strong>
	<%= @user.description %> 
  
</p>
<p>
<strong>Age:</strong>
  <%= @user.age %>
</p>
<p>
<strong>Country:</strong>
  <%= @user.country %>
</p>


<%- if current_user.try(:admin) or @user.id == current_user.try(:id) %>
	<%= link_to 'Edit', edit_user_registration_path(@user) %>
<% end %>

<%= link_to 'Back', users_path %>


</div>
<div id="descriptiondiv">

<h3> Funded Projects </h3>
<p id="notice"><%= notice %></p>


<table>
  <thead>
	    <tr>
	      <th>Title</th>
	      
	      <th>Donationamount</th>
	      <th>Category</th> 
		<th> amount </th>
		<th colspan="3"></th>
	    </tr>
	  </thead>
  
    <% @user_fund_projects.each do |user_fund_projects| %>
      <tr>
	<% if user_fund_projects.user_id == current_user.id %>
	
	  

	  <tbody>
	    <% @projects.each do |project| %>
		<% if user_fund_projects.project_id == project.id %>
	      <tr>
		<td><%= project.title %></td>
		
		<td><%= project.donationamount %></td>
		<td><%= project.category.name %></td>
		
		<td><%= user_fund_projects.amount %></td>
		<td><%= link_to 'Show', project %></td>
	      </tr>
	    <% end %>
		<% end %>
	  </tbody>
	
		<% end %>
	      </tr>
    <% end %>
</table>


	
</div>
<div id="divbottom">
<h2> Projects created by this user: </h2>
<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Donation amount</th>
      <th>Category</th>
      <th>User</th>
      <th>Deliverydate</th>
      <th>Promise</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
	<% if project.user_id == @user.id %>
	
	      <tr>
		<td><%= project.title %></td>
		<td><%= project.description %></td>
		<td><%= project.donationamount %></td>
		<td><%= project.category.name %></td>
		<td><%= project.user_id %></td>
		<td><%= project.deliverydate %></td>
		<td><%= project.promise_id %></td>
		<td><%= link_to 'Show', project %></td>
		<%- if project.user_id == current_user.try(:id) or current_user.try(:admin) %>
			<td><%= link_to 'Edit', edit_project_path(project) %></td>
			<td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
		<% end %>
	      </tr>
	<% end %>
    <% end %>
  </tbody>
</table>

</div>